version: '3.8'

services:
  optimistic-locking-pod-one-example:
    build:
      context: .
      dockerfile: src/OptimisticLockingPodOneExample/Dockerfile
    container_name: optimistic-locking-pod-one-example
    volumes:
      - .:/etc/data
    networks:
      - back-tier

  optimistic-locking-pod-two-example:
    build:
      context: .
      dockerfile: src/OptimisticLockingPodTwoExample/Dockerfile
    container_name: optimistic-locking-pod-two-example
    volumes:
      - .:/etc/data
    networks:
      - back-tier

  pessimistic-locking-pod-one-example:
    build:
      context: .
      dockerfile: src/PessimisticLockingPodOneExample/Dockerfile
    container_name: pessimistic-locking-pod-one-example
    volumes:
      - .:/etc/data
    networks:
      - back-tier

  pessimistic-locking-pod-two-example:
    build:
      context: .
      dockerfile: src/PessimisticLockingPodTwoExample/Dockerfile
    container_name: pessimistic-locking-pod-two-example
    volumes:
      - .:/etc/data
    networks:
      - back-tier

networks:
  back-tier: {}

